version: '3.7'
services: 
    web:
        environment:         
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - /c/Users/mveer/frontend:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev        
        volumes: 
            - /app/node_modules
            - /c/Users/mveer/frontend:/app   
        command: ["npm", "run" ,"test"]
    